### PR TITLE
Udpated the tests for RHEL7 to use inspec resources and tried to use …

### PR DESCRIPTION
**Pull request by aaronlippold**
I left the failing tests where updates to the lockdown scripts need to be updated a bit.

I believe I closed most of the open issues in the tests. 

The primary fix is needed for the users in /etc/shadow and the min, max and warn days. I think the chef recipe should update these entries in the /etc/shadow file as well to fully implement the remediation.

The /var and /var/tmp issue should work once you add the entry as in the comments. Once you update that, you should be able to use the mount resource to ensure that both mount paths point to the same device. 

I also added a small line in the .kitchen.yml file to ensure that inspec runs as 'sudo'.

I also added attributes to the tests so that in the event a system needed to add or subtract audit_rules, or other simular items that it could be done without having to modify the tests.

I fixed the regex in the audit and rsyslog rules as well, as they were, it could have produced bad results because the command statement with the ```should contain``` match would have passed even if the line was ```#``` out. I changed them to strait regex's with stronger matching to ensure that was not possible.

One suggestion, If you used the full InSpec control format, though it forces you to be a bit more verbose, you would gain two major wins: 

( I put an example in sshd_config_sepc.rb for your review - you can see how it may be used if you use the ```inspec exec ./rhel7/controls/. —controls=“sshd-config-2” —format=json-full``` )

1) You can use the TAGS to link all your traceability for the CIS indexes into the controls and link it directly rather than as comments in the files - I was doing this as well until we added tags to inspec :).

2) Decrease your overall upkeep by having a 'core' set of controls for both RHEL6/7 and then just create the RHEL6 and RHEL7 profiles using inheritance. This would allow you to have a single source for your common tests and just 'include' them in each profile so when you make a fix, improvement etc. you only have to do it once. We are using this approach on most of the dev-sec profiles.

### CODE REVIEW

**Comment by isuftin** [comment]
@aaronlippold Sorry it took a while to get to this. I've made a PR to your fork to ensure that Travis CI passes. I will comment on your PR content soon. Trying to dive into the changes themselves.

**Comment by isuftin** [comment]
@aaronlippold 

- Could you expand a bit on what you mean in regards to /etc/shadow. I'm having a bit of trouble following. Which recipe, specifically, are you referring to?

- In regards to the /tmp, /var/tmp fix, I will definitely take a look at that in the next iteration of development for this cookbook. Also, do feel free to make a separate PR for that if you do use this cookbook and want that in a release sooner

- Adding sudo for inspec operations, does this fix something? 

- Loving the attributes! I will start using this in other tests that need something like this! Thank you

- Regex fixes. I suck at Regex, so there's that :) This fix makes much sense

- Thank you for adding a control sample for inspec. I was trying to wrap my head around how this works with Kitchen a month or two ago but gave up since I also wasn't seeing what advantages this gives me. WIth the command snippet you provided, is ./rhel7 a directory local to you? This was not checked in to this PR. 

- Re: Tags. I've given up on trying to keep up with CIS recommendation IDs. They seem to change them around with each version of the publications. They also forbade using their recommendation text as part of my cookbook so it's difficult to do any sort of tracing back to their recommendations. Do you have an example of you using tags in this manner?

- Control inheritance. Could you link me to an example of your use of this? Less maintenance is always desirable

**Comment by aaronlippold** [comment]
@isuftin Sure no problem. Sorry I didn't respond right away. For some reason I am not getting my github notices in gmail so I am not sure what is going on. I will respond inline above if I can :)

**Comment by aaronlippold** [comment]
1. Could you expand a bit on what you mean in regards to /etc/shadow. I'm having a bit of trouble following. Which recipe, specifically, are you referring to?

a. You need to have chef also loop through the users - like inspec is doing - and also ensure that all the user entries in /etc/shaddow also have the mindays, maydays etc set as well. see: http://www.tldp.org/HOWTO/Shadow-Password-HOWTO-7.html#7.2 as an example, but basically if you don't update /etc/shadow as well the implementation has a small hole in it.

2. In regards to the /tmp, /var/tmp fix, I will definitely take a look at that in the next iteration of development for this cookbook. Also, do feel free to make a separate PR for that if you do use this cookbook and want that in a release sooner

a. No worries, just trying to help you close a few issues while I was there.

3. Adding sudo for inspec operations, does this fix something?

a. Right now we are working on cleaning up the resources in inSpec to be a bit better as letting you know if a test fails because your user doesn't have read access to a file or dir. Given you were looking at /etc files and root owned files, since you could run these tests as either root or a user with sudo adding sudo ensures that if your user has sudo it uses it - if its root - it just ignores the sudo option.

4. Loving the attributes! I will start using this in other tests that need something like this! Thank you

a. Great, I am glad they help. I figured if you had to rework the RHEL6 side it would give you enough work in these new approaches to grok them in your fingers.

5. Regex fixes. I suck at Regex, so there's that :) This fix makes much sense. 

a. Great, it actually provided us some good examples of common things to watch out for in some of our classes, and good examples of false positives and corner cases that show the importance of unit tests and code coverage.

6. Thank you for adding a control sample for inspec. I was trying to wrap my head around how this works with Kitchen a month or two ago but gave up since I also wasn't seeing what advantages this gives me. WIth the command snippet you provided, is ./rhel7 a directory local to you? This was not checked in to this PR.

a. I think maybe I didn't merge stuff quite right, go ahead and put things in the right place, no worries.

7. Re: Tags. I've given up on trying to keep up with CIS recommendation IDs. They seem to change them around with each version of the publications. They also forbade using their recommendation text as part of my cookbook so it's difficult to do any sort of tracing back to their recommendations. Do you have an example of you using tags in this manner?

a. So which guidance are you using as your baseline? The STIG itself or an organization adapted version. Primary tag for each of your controls. This may be a good thing to talk about on the phone given it could be a little complex but once we get it untangled I am sure it will be clear.

8. Control inheritance. Could you link me to an example of your use of this? Less maintenance is always desirable

a. https://github.com/chef/inspec/tree/master/examples/meta-profile , so the idea here is that when you find that both a RHEL6 and RHEL7 'control' uses the same test ( except for the value of an attribute perhaps ) that you can put that control in the 'core-profile' and just have the profile include it from the same source in both the RHEL6 and RHEL7 profiles.

**Comment by aaronlippold** [comment]
Any updates on getting this merged?

**Comment by aaronlippold** [comment]
As a note you may also find this example useful: https://github.com/dev-sec/linux-patch-baseline and https://github.com/chris-rock/acme-inspec-profile

**Comment by isuftin** [comment]
@aaronlippold Done! Thank you for that contrib. I've been starting to also build out and use inspec testing in my other cookbooks as well. I appreciate the knowledge sharing!

**Comment by aaronlippold** [comment]
@isuftin cool. I am going to start working on a core rhel7 profile that we want to push to the community. Right how we have at least three different github projects with diverging implementations. We are going to start working with the SIMP project and I am hoping we can start working how we handle the cross use of core profiles across projects.

**Pull request merged**
